### ISSUE TITLE
Provide how-to in the readme to use the generator

### ISSUE THREAD

**Issue by apupier** [fabric8-launcher/launcher-vscode-extension#12]
available in UI? Which menu?
available from the palette? Which commands?

**Comment by apupier** [comment]
it is available from palette:
![image](https://user-images.githubusercontent.com/1105127/46288516-43e26480-c586-11e8-8bbd-6e90e7a13e4e.png)

**Comment by jeffmaury** [comment]
@valdar is this still relevant ?

**Comment by apupier** [comment]
no, the readme contains an how to now.
